version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - PORT_FASTIFY=3000
      - PORT_EXPRESS=3001
      - MONGODB_URI=mongodb+srv://develop:Yeu0Ytcb6IfKjhmm@cluster0.6xvqrgt.mongodb.net/users-db
      - JWT_SECRET=test-secret@@123
